emdat_web/apps/stats/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^emdat_output$', views.emdat_output, name='emdat_output'),
]

emdat_web/settings/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.experiment.urls', namespace='experiment')),
    url(r'^stats/', include('apps.stats.urls', namespace='stats')),
    url(r'^documentation/', include('apps.documentation.urls', namespace='documentation'))
]

emdat_web/apps/stats/forms.py
from django import forms


class StatsForm(forms.Form):
    participants = forms.Field(label='Participants (max. 12) ',required=True)
    features = forms.Field(label='Features', required=True)
    aoi_features = forms.Field(label='AOI Features',required=True)

emdat_web/apps/stats/views.py
import os
from django.http import FileResponse
from django.conf import settings
from django.shortcuts import render
from ..commons.utility import get_features_by_category, get_info_feature, read_aoi_file, get_participants_ids, get_emdat_output_file
from .forms import StatsForm


def index(request):
    """
    Show visualization interface
    """

    stats_form = StatsForm

    error_files_messages = []
    column_participant =  settings.EMDAT_COLUMN_PARTICIPANT
    emdat_output_folder =  os.path.join(settings.BASE_DIR, settings.EMDAT_OUTPUT_FOLDER)
    participants_ids = []

    # List output files with different eye trackers
    list_output_files = []
    list_output_files.append(os.path.join(emdat_output_folder, settings.EMDAT_OUTPUT_FILE_TOBII))
    list_output_files.append(os.path.join(emdat_output_folder, settings.EMDAT_OUTPUT_FILE_TOBIIV3))
    list_output_files.append(os.path.join(emdat_output_folder, settings.EMDAT_OUTPUT_FILE_SMI))

    # Search EMDAT output files
    emdat_output_file = get_emdat_output_file(list_output_files)
    print(emdat_output_file)

    # Get list of participants or append error
    if (emdat_output_file):
        participants_ids = get_participants_ids(emdat_output_file, column_participant)
    else:
        error_files_messages.append('EMDAT output file')

    # Get list of AOI
    aoi_file =  os.path.join(settings.BASE_DIR, settings.EMDAT_AOI_FILE)
    aoi_names = []

    if (os.path.exists(aoi_file)):
        aoi_names = read_aoi_file(aoi_file)
    else:
        error_files_messages.append('Definition of AOI file')

    # Get list of features by category
    all_features = get_features_by_category()

    # Options selected
    selected_participants, selected_features, selected_features_info, selected_aoi_features = [], [], [], []

    # Flag to indicate if plot 1 or 2 charts per row
    panel_small = True

    # If EMDAT output file exist and if is a POST request
    if not error_files_messages and request.method == 'POST':
        selected_participants = [int(participant) for participant in request.POST.getlist('select_participants')]

        if len(selected_participants) > 6:
           panel_small = False

        selected_features = [str(feature) for feature in request.POST.getlist('select_features')]
        selected_features_info = [get_info_feature(feature) for feature in selected_features]

        #selected_aoi_features = []

    return render(request, 'stats/index.html', {'stats_form':stats_form,
                                                'aoi_names':aoi_names,
                                                'error_files_messages':error_files_messages,
                                                'column_participant':column_participant,
                                                'participants_ids':participants_ids,
                                                'selected_participants':selected_participants,
                                                'selected_features':selected_features,
                                                'selected_features_info':selected_features_info,
                                                'selected_aoi_features':selected_aoi_features,
                                                'gaze_features':all_features['gaze'],
                                                'aoi_features':all_features['aoi'],
                                                'pupil_features':all_features['pupil'],
                                                'distance_features':all_features['distance'],
                                                'events_features':all_features['events'],
                                                'panel_small':panel_small})


def emdat_output(request):
    """
    Returns the EMDAT output CSV file
    """

    emdat_output_folder =  os.path.join(settings.BASE_DIR, settings.EMDAT_OUTPUT_FOLDER)

    # List output files with different eye trackers
    list_output_files = []
    list_output_files.append(os.path.join(emdat_output_folder, settings.EMDAT_OUTPUT_FILE_TOBII))
    list_output_files.append(os.path.join(emdat_output_folder, settings.EMDAT_OUTPUT_FILE_TOBIIV3))
    list_output_files.append(os.path.join(emdat_output_folder, settings.EMDAT_OUTPUT_FILE_SMI))

    # Search EMDAT output files
    emdat_output_file = get_emdat_output_file(list_output_files)

    response = FileResponse(open(emdat_output_file, 'rb'))
    response['Content-Disposition'] = 'attachment; filename="emdat.csv"'

    return response

emdat_web/apps/stats/templates/stats/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} Visualization {% endblock %}

{% block menu %}
    {% include 'menu.html' with active_menu='stats' %}
{% endblock %}

{% block head_files_compress %}
    <link rel="stylesheet" href="{% static "stats/css/plugins/multiselect/bootstrap-multiselect.css" %}">
    {# CSS for this app #}
    <link rel="stylesheet" href="{% static 'stats/css/stats.css' %}">
{% endblock %}

{% block content %}
    <div class="row well">
        <div class="col-xs-10 stats-panel">
            <form id="stats-form" class="form-inline" method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-sm-4">
                        <label for="select_participants">{{ stats_form.participants.label }} {% if stats_form.participants.field.required %} *{% endif %}</label> <br>
                        <select name="select_participants" id="select_participants" multiple="multiple">
                            <option value="0" {% if 0 in selected_participants %}selected{% endif %}>Average</option>
                            <option data-role="divider"></option>
                            {% for participant in participants_ids %}
                                <option value="{{ participant }}" {% if participant in selected_participants %}selected{% endif %}>{{ participant }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="col-sm-4">
                        <label for="select_features">{{ stats_form.features.label }} {% if stats_form.features.field.required %} *{% endif %}</label> <br>
                        <select name="select_features" id="select_features" multiple="multiple">
                            <option data-role="divider" disabled></option>
                            <optgroup label="All gaze">
                                {% for feature in gaze_features %}
                                    <option value="{{ feature.key }}" {% if feature.key in selected_features %}selected{% endif %}>{{ feature.name }}</option>
                                {% endfor %}
                            </optgroup>
                            <option data-role="divider" disabled></option>
                            <optgroup label="All pupil">
                                {% for feature in pupil_features %}
                                    <option value="{{ feature.key }}" {% if feature.key in selected_features %}selected{% endif %}>{{ feature.name }}</option>
                                {% endfor %}
                            </optgroup>
                            <option data-role="divider" disabled></option>
                            <optgroup label="All distance">
                                {% for feature in distance_features %}
                                    <option value="{{ feature.key }}" {% if feature.key in selected_features %}selected{% endif %}>{{ feature.name }}</option>
                                {% endfor %}
                            </optgroup>
                            <option data-role="divider" disabled></option>
                            <optgroup label="All Events">
                                {% for feature in events_features %}
                                    <option value="{{ feature.key }}" {% if feature.key in selected_features %}selected{% endif %}>{{ feature.name }}</option>
                                {% endfor %}
                            </optgroup>
                        </select>
                    </div>

                    <div class="col-sm-4">
                        <label for="select_aoi_features">{{ stats_form.aoi_features.label }} {% if stats_form.aoi_features.field.required %} *{% endif %}</label> <br>
                        <select name="select_aoi_features" id="select_aoi_features" multiple="multiple">
                            {% for aoi in aoi_names %}
                                <option data-role="divider" disabled></option>
                                <optgroup label="{{ aoi }}">
                                    {% for feature in aoi_features %}
                                        <option value="{{ aoi }}_{{ feature.key }}" {% if aoi|add:'_'|add:feature.key in selected_aoi_features %}selected{% endif %}>{{ feature.name }}</option>
                                    {% endfor %}
                                </optgroup>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="generate row">
                    <div class="col-xs-10">
                        <div class="stats-errors"></div>
                    </div>
                    <div class="col-xs-2 text-right">
                        <button type="submit" class="btn btn-success">Generate</button>
                    </div>
                </div>

            </form>
        </div>

        {# Replay buttons #}
        <div class="col-xs-2">
            <div class="row text-center buttons">
                <div class="col-xs-6">
                    <i class="fa fa-play-circle fa-3x"></i>
                    <span>Play</span>
                </div>
                <div class="col-xs-6">
                    <i class="fa fa-stop-circle fa-3x"></i>
                    <span>Stop</span>
                </div>
            </div>
        </div>
    </div>

    {% if error_files_messages %}
        <div class="row">
            <div class="alert alert-danger">
                <p>Please ensure that you have the following files in the output folder:</p>
                <ul>
                    {% for message in error_files_messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}

    {# Charts #}
    <div class="row" id="charts_panel">
        {% for feature in selected_features_info %}
            <div class="{% if panel_small %}col-md-6{% else %}col-md-12{% endif %} chart-emdat">
                <div class="panel panel-primary" id="{{ feature.key }}">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            {{ feature.name }}
                            <span class="close pull-right" data-toggle="tooltip" data-title="Delete" data-id="{{ feature.key }}"><i class="fa fa-times"></i></span>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div class="pull-right">
                            <a class="save-chart" id="save_{{ feature.key }}" href="javascript:"><i class="fa fa-save"></i> Save</a>
                            <a class="sort-chart" id="sort_{{ feature.key }}" href="javascript:"><i class="fa fa-sort-amount-asc"></i> Sort</a>
                        </div>
                        <div id="barchart_{{ feature.key }}"></div>
                    </div>
                </div>
            </div>
        {% endfor %}

        {# Hidden canvas to export charts #}
        <canvas id="canvas_export" width="{% if panel_small %}550{% else %}850{% endif %}px" height="250px"></canvas>

    </div>

    {# TEST Line charts #}
    <!--
    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-primary" id="linechart">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Mean Pupil Size
                        <span class="close pull-right" data-toggle="tooltip" data-title="Delete" data-id="linechart"><i class="fa fa-times"></i></span>
                    </h3>
                </div>
                <div class="panel-body">
                    <div id="linechart_meanpupilsize">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="panel panel-primary" id="linechart">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Mean Distance
                        <span class="close pull-right" data-toggle="tooltip" data-title="Delete" data-id="linechart"><i class="fa fa-times"></i></span>
                    </h3>
                </div>
                <div class="panel-body">
                    <div id="linechart_meandistance">

                    </div>
                </div>
            </div>
        </div>
    </div>
    -->


    {# Button to scroll up #}
    <a href="#" class="back-to-top">Back to Top </a>

{% endblock %}

{% block files_before_bootstrap %}
    {# Jquery UI before bootstrap to avoid problems with tooltips #}
    <script src="{% static 'stats/js/jquery-ui.min.js' %}"></script>
{% endblock %}

{% block body_files %}
    <script src="{% static 'stats/js/plugins/d3/d3.min.js' %}"></script>
    <script src="{% static 'stats/js/plugins/W/W.min.js' %}"></script>
{% endblock %}

{% block body_files_compress %}
    <script src="{% static 'stats/js/plugins/multiselect/bootstrap-multiselect.js' %}"></script>
    <script src="{% static 'stats/js/plugins/d3/d3-tip.js' %}"></script>
    <script src="{% static 'experiment/js/plugins/validate/jquery.validate.min.js' %}"></script>
    {# JS for this app #}
    <script src="{% static 'stats/js/stats.js' %}"></script>

    <script type="text/javascript">

        $(document).ready(generateAllCharts('{% url 'stats:emdat_output' %}', {{ selected_participants }}, {{ selected_features_info|safe }}, '{{ column_participant }}'));

        /*
        sparkline = [];

        sparkline['meanpupilsize'] = new LineChart('meanpupilsize', 0, 1, 12);
        sparkline['meandistance'] = new LineChart('meandistance', 200, 850, 12);


        function pollFeatures() {
            $.getJSON("http://127.0.0.1:8001/trackers/TT120-204-80900268/get_features", null, function (data) {
                var features = "";
                for (var key in data) {
                    if (data.hasOwnProperty(key)) {
                        if (key in sparkline && key != "length") {
                            sparkline[key].addData([Number(data[key])]);
                        }
                    }
                }

            })
            .fail(function(jqXHR, textStatus, errorThrown) {
                        sparkline['meanpupilsize'].addData([0]);
                        sparkline['meandistance'].addData([0]);
                    });
        }

        $(document).ready(function () {
            setInterval(pollFeatures, 1000);
            /*sparkline['meandistance'].addData([Number(200)]);
            sparkline['meandistance'].addData([Number(600)]);
            sparkline['meandistance'].addData([Number(500)]);

        });
        */

    </script>

{% endblock %}