emdat_web/apps/experiment/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.settings, name='settings_experiment'),
]

emdat_web/apps/stats/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^emdat_output$', views.emdat_output, name='emdat_output'),
]

emdat_web/settings/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.experiment.urls', namespace='experiment')),
    url(r'^stats/', include('apps.stats.urls', namespace='stats')),
    url(r'^documentation/', include('apps.documentation.urls', namespace='documentation'))
]

emdat_web/templates/base.html
{% load bootstrap3 %}
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} Home {% endblock %} - EMDAT</title>

    {# Load Bootstrap CSS #}
    {% bootstrap_css %}

    <link href="{% static 'css/font_awesome/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

    <script src="{% static 'js/theme/jquery.min.js' %}"></script>

    {# Block for CSS files #}
    {% block head_files %}{% endblock %}

    {# Compresses linked and inline CSS  #}
    {% compress css %}
        {% block head_files_compress %}{% endblock %}
    {% endcompress %}
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'experiment:settings_experiment' %}">Eye Movement Data Analysis Toolkit (EMDAT)</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% block menu %} {% endblock %}
            </ul>
        </div>
    </div>
</nav>

<div class="container" style="padding-top: 70px">
    <div class="text-center">
        <h1>{% block page_title %} {% endblock %}</h1>
    </div>
    <div class="col-lg-12">
        {% block content %}{% endblock %}
    </div>
</div>

{% block files_before_bootstrap %}{% endblock %}

{# Load Bootstrap JavaScript #}
{% bootstrap_javascript %}

<script src="{% static 'js/plugins/toastr/toastr.min.js' %}"></script>

{% block body_files %}{% endblock %}

{# Compresses linked and inline JS #}
{% compress js %}
    <script>
        {# Toastr messages #}
        {% if messages %}
            {% for message in messages %}
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    timeOut: 6000
                };
                title_message = "{{ message.tags }}";
                toastr["{{ message.tags }}"]('{{ message }}', title_message.toUpperCase());
            {% endfor %}
        {% endif %}
    </script>
    {% block body_files_compress %}{% endblock %}
{% endcompress %}

</body>
</html>

emdat_web/templates/menu.html
<li class="{% if active_menu == 'settings' %}active{% endif %}"><a href="{% url 'experiment:settings_experiment' %}">Settings</a></li>
<li class="{% if active_menu == 'stats' %}active{% endif %}"><a href="{% url 'stats:index' %}">Visualization</a></li>
<li class="{% if active_menu == 'documentation' %}active{% endif %}"><a href="{% url 'documentation:index' %}">Documentation</a></li>